DROP DATABASE IF EXISTS Users_CRUD;
CREATE DATABASE Users_CRUD;
USE Users_CRUD;
CREATE Table users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  firstName VARCHAR(20) NOT NULL,
  lastName VARCHAR(20) NOT NULL,
  email VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL
) engine = InnoDB;